name: Check markdown files for broken links
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.md

      - name: Check Markdown Links
        id: broken-markdown-files
        uses: jwr0/markdown-link-checker@add-json-output
        with:
          files: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
          timeout: "5"
          retry-count: "1"

      - name: Comment on PR in case of broken links
        if: ${{ failure() }}
        run: |
          set -x
          echo "${{ steps.broken-markdown-files.outputs.json }}" > /tmp/file_list.json
          cat /tmp/file_list.json
          for item in $(cat /tmp/file_list.json | jq '.[] | @base64')
          do
            LINK="$(echo "$item" | base64 --decode | jq -r .link)"
            FILE="$(echo "$item" | base64 --decode | jq -r .file)"
            LINE_NUM="$(echo "$item" | base64 --decode | jq -r .line_num)"

            gh api \
              -method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/pulls/${{ github.event.number }}/comments \
              -f "body=The link for $LINK is broken." \
              -f "commit_id=${{ github.event.pull_request.head.sha }}" \
              -f "path=$FILE" \
              -F "line=$LINE_NUM"
          done
        env:
          GH_TOKEN: ${{ github.token }}

